baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'LDFJ Personal Blog'

[params]
    [params.author]
        name = 'Luis David Fuentes Juvera'
        mail = 'luis@mail.com'
        github = 'https://github.com/LuisDFJ'
        linkedin = 'https://linkedin.com'

[security]
    [security.exec]
        allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^babel$']
